# Generated by Django 2.2.2 on 2019-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Employee ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_email', models.EmailField(blank=True, max_length=254)),
                ('date_of_entry', models.DateField(auto_now=True)),
                ('emp_persona', models.CharField(max_length=2)),
                ('emp_state', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-date_of_entry'],
            },
        ),
    ]
